### ISSUE TITLE
Stand-alone mode only - The v1 bosh-release doesn't not support bosh deploy --recreate

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/mongodb-boshrelease#18]
The BOSH message is : 
...
Using deployment 'mongodb'

Task 1020779

16:10:35 | Preparing deployment: Preparing deployment (00:00:01)
16:10:38 | Preparing package compilation: Finding packages to compile (00:00:00)
16:10:38 | Updating instance mongodb-broker: mongodb-broker/76e11b9d-9e14-4788-88fa-8ead0f28267f (0) (canary)
16:10:38 | Updating instance mongod: mongod/201cd9f6-84e7-483d-b978-136afad86d17 (0) (canary)
16:13:16 | Updating instance mongodb-broker: mongodb-broker/76e11b9d-9e14-4788-88fa-8ead0f28267f (0) (canary) (00:02:38)
17:13:48 | Updating instance mongod: mongod/201cd9f6-84e7-483d-b978-136afad86d17 (0) (canary) (01:03:10)
            L Error: Action Failed get_task: Task 13482112-ace9-4174-5373-7bab3952615b result: 1 of 4 pre-start scripts failed. Failed Jobs: mongod. Successful Jobs: login_banner, syslog_forwarder, ca_certs.

17:13:48 | Error: Action Failed get_task: Task 13482112-ace9-4174-5373-7bab3952615b result: 1 of 4 pre-start scripts failed. Failed Jobs: mongod. Successful Jobs: login_banner, syslog_forwarder, ca_certs.

Started  Fri Dec  1 16:10:35 UTC 2017
Finished Fri Dec  1 17:13:48 UTC 2017
Duration 01:03:13

Task 1020779 error

Changing state:
  Expected task '1020779' to succeed but state is 'error'

Exit code 1
...

The deployment is configured as standalone.
The problem seems to be located in the pre-start script of the mongod job.
There is an infinite loop in the function "create_admin_users".

**Comment by jraverdy-orange** [comment]
the problem doesn't seems to affect replicaset deployments
bosh deploy -d mongodb-rs-nossl -v appli=mongodb-rs-nossl manifest-rs-nossl.yml --recreate
Using environment '10.165.0.8' as user 'jeremy' (openid, bosh.admin)

Using deployment 'mongodb-rs-nossl'

Continue? [yN]: y

Task 306750

Task 306750 | 14:32:27 | Preparing deployment: Preparing deployment (00:00:02)
Task 306750 | 14:32:31 | Preparing package compilation: Finding packages to compile (00:00:00)
Task 306750 | 14:32:31 | Updating instance mongod: mongod/01bc982c-1d4f-48fc-90a9-5c916fa71405 (0) (canary) (00:06:03)
Task 306750 | 14:38:34 | Updating instance mongod: mongod/4aea1900-16ca-422a-a317-8a2c4d00d612 (1) (00:06:01)
Task 306750 | 14:44:35 | Updating instance mongod: mongod/dea1ad99-f2c3-4a2b-8aaf-ac0e50df276d (2) (00:06:02)

Task 306750 Started  Fri Dec  8 14:32:27 UTC 2017
Task 306750 Finished Fri Dec  8 14:50:37 UTC 2017
Task 306750 Duration 00:18:10
Task 306750 done

Succeeded

**Comment by jraverdy-orange** [comment]
Fixed by PR #20
