### ISSUE TITLE
Support root password rotation

### ISSUE THREAD

**Issue by JCL38-ORANGE** [orange-cloudfoundry/mongodb-boshrelease#60]
### Expected behavior
As a mongodb service operator, in order to protect my platform, I need sometimes to perform password regeneration.

### Observed behavior
credhub regenerate -n "path to mongodb root password"
After regeneration, neither deploy, neither recreate can be done on deployments.
The following error is raised : 
 Task 2359451 | 12:29:06 | Updating instance mongod: mongod/48713cb5-ac31-41ea-b451-ed087a63a432 (0) (canary) (00:00:41)
14:29:47
	
                     L Error: Action Failed get_task: Task 63022b42-c6c7-4b1c-4fe4-0f2146d83e89 result: 1 of 6 pre-start scripts failed. Failed Jobs: mongod. Successful Jobs: login_banner, bpm, bosh-dns, syslog_forwarder, ca_certs.
14:29:47
	
Task 2359451 | 12:29:47 | Error: Action Failed get_task: Task 63022b42-c6c7-4b1c-4fe4-0f2146d83e89 result: 1 of 6 pre-start scripts failed. Failed Jobs: mongod. Successful Jobs: login_banner, bpm, bosh-dns, syslog_forwarder, ca_certs.
14:29:47

### Affected release
Reproduced on version 6 and 7

**Comment by jraverdy-orange** [comment]
closed in v9
