### ISSUE TITLE
Unable to git clone

### ISSUE THREAD

**Issue by Gurusairam001** [orange-cloudfoundry/mongodb-boshrelease#71]
Hi Team,

I'm unable to clone the repo. it is failing at the submodule mongodb-quota-enforcer
![image](https://user-images.githubusercontent.com/54388782/76592038-0f632e00-6518-11ea-805e-7156ced1cbd8.png)

Please look into it.

**Comment by poblin-orange** [comment]
hi @Gurusairam001. Sorry for the delay, we will soon solve. You can clone on v8 for the time being.

**Comment by JCL38-ORANGE** [comment]
Hello @Gurusairam001,
You must use the v7 release because the v8 can't be used in production (data migration is not taken into account).
Please checkout the v7 tag.
Regards,
Jean-Christophe.

**Comment by JCL38-ORANGE** [comment]
Closed with v10 release.
